# Generated by Django 5.0.6 on 2025-01-31 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=70)),
                ('quantity', models.IntegerField()),
                ('customer_number', models.IntegerField(max_length=30)),
                ('purshasing_price', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 1, 31, 18, 49, 14, 229611), editable=False)),
            ],
        ),
    ]
